id: cors-misconfig

info:
  name: CORS Misconfiguration
  author: nadino,g4l1t0,convisoappsec,pdteam
  severity: info
  reference:
    - https://portswigger.net/web-security/cors
    - https://www.corben.io/advanced-cors-techniques/
    - https://www.geekboy.ninja/blog/exploiting-misconfigured-cors-cross-origin-resource-sharing/
  tags: cors,generic,misconfig

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{FQDN}}
        Origin: {{cors_origin}}

    payloads:
      cors_origin:
        - "https://{{rand_base(5)}}.com"                      # Arbitrary domain
        - "https://{{RDN}}.{{tolower(rand_base(5))}}.com"     # Arbitrary domain
        - "https://{{RDN}}{{tolower(rand_base(5))}}.com"      # Arbitrary domain
        - "https://{{RDN}}_.{{tolower(rand_base(5))}}.com"    # Arbitrary domain
        - "https://{{RDN}}%60.{{tolower(rand_base(5))}}.com"  # Arbitrary domain
        - "https://{{tolower(rand_base(5))}}.com.{{RDN}}"     # Arbitrary subdomain
        - "http://{{tolower(rand_base(5))}}.com.{{RDN}}"      # Arbitrary subdomain over HTTP
        - "null"                                              # null origin

    stop-at-first-match: true
    matchers-condition: or
    matchers:
      - type: dsl
        name: arbitrary-origin
        dsl:
          - "contains(tolower(all_headers), 'access-control-allow-origin: {{cors_origin}}')"
          - "contains(tolower(all_headers), 'access-control-allow-credentials: true')"
        condition: and

      - type: dsl
        name: wildcard-origin
        dsl:
          - "contains(tolower(all_headers), 'access-control-allow-origin: *')"
          - "!contains(tolower(all_headers), 'access-control-allow-credentials: true')"
        condition: and